version: '3.8'

services:
  postgres:
    image: postgres:17.6-bookworm
    container_name: blog_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ndv@22092005
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  blogapi:
    build: .
    container_name: blogapi
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blogdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ndv@22092005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - blog-network

volumes:
  pgdata:


networks:
  blog-network:
