version: '3.8'
services:
  postgres:
    image: postgres:17.6-bookworm
    container_name: blog_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ndv@22092005
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  blogapi:
    build: .
    container_name: blogapi
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: blogdb
      DB_USER: postgres
      DB_PASSWORD: Ndv@22092005
    ports:
      - "8080:8080"

volumes:
  pgdata:
